/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.com.dominik.dabrowski.kalkulatordd;

/**
 *
 * @author admin
 */
public class Kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButtonLiczba1 = new javax.swing.JButton();
        jButtonLiczba4 = new javax.swing.JButton();
        jButtonLiczba7 = new javax.swing.JButton();
        jButtonLiczba8 = new javax.swing.JButton();
        jButtonLiczba2 = new javax.swing.JButton();
        jButtonLiczba5 = new javax.swing.JButton();
        jButtonLiczba0 = new javax.swing.JButton();
        jButtonWynik = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButtonLiczba9 = new javax.swing.JButton();
        jButtonMnozenie = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jButtonLiczba3 = new javax.swing.JButton();
        jButtonLiczba6 = new javax.swing.JButton();
        jButtonPrzecinek = new javax.swing.JButton();
        jButtonDzielenie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));

        jButtonLiczba1.setBackground(new java.awt.Color(255, 153, 51));
        jButtonLiczba1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonLiczba1.setText("1");
        jButtonLiczba1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLiczba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiczba1ActionPerformed(evt);
            }
        });

        jButtonLiczba4.setBackground(new java.awt.Color(255, 153, 51));
        jButtonLiczba4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonLiczba4.setText("4");
        jButtonLiczba4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLiczba4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiczba4ActionPerformed(evt);
            }
        });

        jButtonLiczba7.setBackground(new java.awt.Color(255, 153, 51));
        jButtonLiczba7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonLiczba7.setText("7");
        jButtonLiczba7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLiczba7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiczba7ActionPerformed(evt);
            }
        });

        jButtonLiczba8.setBackground(new java.awt.Color(255, 153, 51));
        jButtonLiczba8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonLiczba8.setText("8");
        jButtonLiczba8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLiczba8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiczba8ActionPerformed(evt);
            }
        });

        jButtonLiczba2.setBackground(new java.awt.Color(255, 153, 51));
        jButtonLiczba2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonLiczba2.setText("2");
        jButtonLiczba2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLiczba2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiczba2ActionPerformed(evt);
            }
        });

        jButtonLiczba5.setBackground(new java.awt.Color(255, 153, 51));
        jButtonLiczba5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonLiczba5.setText("5");
        jButtonLiczba5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLiczba5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiczba5ActionPerformed(evt);
            }
        });

        jButtonLiczba0.setBackground(new java.awt.Color(255, 153, 51));
        jButtonLiczba0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonLiczba0.setText("0");
        jButtonLiczba0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLiczba0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiczba0ActionPerformed(evt);
            }
        });

        jButtonWynik.setBackground(new java.awt.Color(255, 153, 51));
        jButtonWynik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonWynik.setText("=");
        jButtonWynik.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonWynik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWynikActionPerformed(evt);
            }
        });

        jButtonPlus.setBackground(new java.awt.Color(255, 153, 51));
        jButtonPlus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonPlus.setText("+");
        jButtonPlus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });

        jButtonLiczba9.setBackground(new java.awt.Color(255, 153, 51));
        jButtonLiczba9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonLiczba9.setText("9");
        jButtonLiczba9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLiczba9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiczba9ActionPerformed(evt);
            }
        });

        jButtonMnozenie.setBackground(new java.awt.Color(255, 153, 51));
        jButtonMnozenie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonMnozenie.setText("x");
        jButtonMnozenie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonMinus.setBackground(new java.awt.Color(255, 153, 51));
        jButtonMinus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonMinus.setText("-");
        jButtonMinus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });

        jButtonLiczba3.setBackground(new java.awt.Color(255, 153, 51));
        jButtonLiczba3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonLiczba3.setText("3");
        jButtonLiczba3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLiczba3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiczba3ActionPerformed(evt);
            }
        });

        jButtonLiczba6.setBackground(new java.awt.Color(255, 153, 51));
        jButtonLiczba6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonLiczba6.setText("6");
        jButtonLiczba6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLiczba6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLiczba6ActionPerformed(evt);
            }
        });

        jButtonPrzecinek.setBackground(new java.awt.Color(255, 153, 51));
        jButtonPrzecinek.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonPrzecinek.setText(",");
        jButtonPrzecinek.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonDzielenie.setBackground(new java.awt.Color(255, 153, 51));
        jButtonDzielenie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonDzielenie.setText("/");
        jButtonDzielenie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonLiczba7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLiczba8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonLiczba1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLiczba2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonLiczba4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLiczba5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLiczba0, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonLiczba3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonMnozenie, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonLiczba9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonLiczba6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonPrzecinek, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonDzielenie, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonLiczba9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonPrzecinek, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDzielenie, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLiczba1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLiczba2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLiczba3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMnozenie, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLiczba5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLiczba4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLiczba6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLiczba7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLiczba8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonWynik, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLiczba0, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String liczba = "";
    private void jButtonLiczba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiczba1ActionPerformed
        jTextField1.setText(liczba+"1");
        liczba=jTextField1.getText();
    }//GEN-LAST:event_jButtonLiczba1ActionPerformed

    private void jButtonLiczba2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiczba2ActionPerformed
        jTextField1.setText(liczba+"2");
        liczba=jTextField1.getText();
    }//GEN-LAST:event_jButtonLiczba2ActionPerformed

    private void jButtonLiczba0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiczba0ActionPerformed
        jTextField1.setText(liczba+"0");
        liczba=jTextField1.getText();
    }//GEN-LAST:event_jButtonLiczba0ActionPerformed

    private void jButtonLiczba3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiczba3ActionPerformed
        jTextField1.setText(liczba+"3");
        liczba=jTextField1.getText();
    }//GEN-LAST:event_jButtonLiczba3ActionPerformed

    private void jButtonLiczba4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiczba4ActionPerformed
        jTextField1.setText(liczba+"4");
        liczba=jTextField1.getText();
    }//GEN-LAST:event_jButtonLiczba4ActionPerformed

    private void jButtonLiczba5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiczba5ActionPerformed
        jTextField1.setText(liczba+"5");
        liczba=jTextField1.getText();
    }//GEN-LAST:event_jButtonLiczba5ActionPerformed

    private void jButtonLiczba6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiczba6ActionPerformed
        jTextField1.setText(liczba+"6");
        liczba=jTextField1.getText();
    }//GEN-LAST:event_jButtonLiczba6ActionPerformed

    private void jButtonLiczba7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiczba7ActionPerformed
        jTextField1.setText(liczba+"7");
        liczba=jTextField1.getText();
    }//GEN-LAST:event_jButtonLiczba7ActionPerformed

    private void jButtonLiczba8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiczba8ActionPerformed
        jTextField1.setText(liczba+"8");
        liczba=jTextField1.getText();
    }//GEN-LAST:event_jButtonLiczba8ActionPerformed

    private void jButtonLiczba9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLiczba9ActionPerformed
        jTextField1.setText(liczba+"9");
        liczba=jTextField1.getText();
    }//GEN-LAST:event_jButtonLiczba9ActionPerformed
    int liczba1;
        int liczba2;
        String znak = "";
    private void jButtonWynikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWynikActionPerformed
        liczba2 = Integer.parseInt(liczba);
        if(znak.equals("+")){
            int wynik = liczba1 + liczba2;
            String tekst = String.valueOf(wynik);
            jTextField1.setText(tekst);
            liczba = "";
        }else if(znak.equals("-")){
            int wynik = liczba1 - liczba2;
            String tekst = String.valueOf(wynik);
            jTextField1.setText(tekst);
            liczba = "";
        }
    }//GEN-LAST:event_jButtonWynikActionPerformed

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        znak = "-";
        liczba1 = Integer.parseInt(liczba);
        liczba ="";
    }//GEN-LAST:event_jButtonMinusActionPerformed

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        znak = "+";
        liczba1 = Integer.parseInt(liczba);
        liczba ="";
    }//GEN-LAST:event_jButtonPlusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDzielenie;
    private javax.swing.JButton jButtonLiczba0;
    private javax.swing.JButton jButtonLiczba1;
    private javax.swing.JButton jButtonLiczba2;
    private javax.swing.JButton jButtonLiczba3;
    private javax.swing.JButton jButtonLiczba4;
    private javax.swing.JButton jButtonLiczba5;
    private javax.swing.JButton jButtonLiczba6;
    private javax.swing.JButton jButtonLiczba7;
    private javax.swing.JButton jButtonLiczba8;
    private javax.swing.JButton jButtonLiczba9;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonMnozenie;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JButton jButtonPrzecinek;
    private javax.swing.JButton jButtonWynik;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
